import { Category, Platform, Prompt } from './types';

export const MOCK_PROMPTS: Prompt[] = [
  // ChatGPT Prompts - Coding
  {
    id: '1',
    title: 'Desarrollador Full Stack Expert',
    description: 'Resuelve problemas complejos de arquitectura web y optimización de código.',
    content: 'Actúa como desarrollador Full Stack Senior con experiencia en React, Node.js y bases de datos. Analiza esta arquitectura y sugiere mejoras en rendimiento, escalabilidad y seguridad: [DESCRIBE TU ARQUITECTURA]. Incluye mejores prácticas, patrones de diseño y code splitting.',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'DevMaster',
    authorId: 'user-1',
    authorPhoto: 'https://ui-avatars.com/api/?name=DevMaster&background=6366f1&color=fff',
    likes: 2450,
    views: 8900,
    tags: ['fullstack', 'react', 'nodejs', 'architecture'],
    createdAt: '2024-01-15'
  },
  {
    id: '2',
    title: 'Debug de Python con IA',
    description: 'Encuentra y corrige bugs en código Python con explicaciones detalladas.',
    content: 'Eres un experto en Python debugging. Analiza este código buscando errores lógicos, memory leaks, problemas de performance y vulnerabilidades de seguridad. Proporciona versión corregida con comentarios explicando cada cambio:\n\n[PEGA TU CÓDIGO PYTHON AQUÍ]',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'PythonPro',
    authorId: 'user-2',
    authorPhoto: 'https://ui-avatars.com/api/?name=PythonPro&background=f59e0b&color=fff',
    likes: 1890,
    views: 6500,
    tags: ['python', 'debugging', 'optimization'],
    createdAt: '2024-02-20'
  },

  // ChatGPT Prompts - Writing
  {
    id: '3',
    title: 'Copywriter Persuasivo',
    description: 'Crea copy de ventas que convierte usando técnicas de neuromarketing.',
    content: 'Actúa como copywriter experto en técnicas de persuasión AIDA, PAS y storytelling. Crea un copy de venta para [PRODUCTO/SERVICIO] que incluya: headline magnético, bullets con beneficios específicos, objeciones resueltas y CTA irresistible. Tono: [profesional/casual/urgente].',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Writing,
    author: 'CopyExpert',
    authorId: 'user-3',
    authorPhoto: 'https://ui-avatars.com/api/?name=CopyExpert&background=ec4899&color=fff',
    likes: 3200,
    views: 12000,
    tags: ['copywriting', 'sales', 'marketing', 'persuasion'],
    createdAt: '2024-01-25'
  },
  {
    id: '4',
    title: 'Email Marketing que Convierte',
    description: 'Secuencias de emails automatizadas con alta tasa de apertura.',
    content: 'Crea una secuencia de 5 emails para automatización de venta de [PRODUCTO]. Email 1: Bienvenida + valor. Email 2: Historia personal. Email 3: Objeciones resueltas. Email 4: Urgencia + scarcity. Email 5: Última oportunidad. Incluye asuntos con alta tasa de apertura (>40%).',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Marketing,
    author: 'EmailPro',
    authorId: 'user-4',
    authorPhoto: 'https://ui-avatars.com/api/?name=EmailPro&background=10b981&color=fff',
    likes: 2100,
    views: 7800,
    tags: ['email', 'automation', 'sales-funnel'],
    createdAt: '2024-02-01'
  },

  // Claude Prompts - Business
  {
    id: '5',
    title: 'Analista de Negocios Estratégico',
    description: 'Análisis FODA y estrategias de crecimiento basadas en datos.',
    content: 'Actúa como consultor de negocios con MBA. Realiza análisis FODA completo de [EMPRESA/PROYECTO]. Incluye: análisis de competencia, tendencias de mercado, oportunidades de crecimiento, riesgos principales y plan de acción con KPIs específicos para próximos 6 meses.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Business,
    author: 'BusinessGuru',
    authorId: 'user-5',
    authorPhoto: 'https://ui-avatars.com/api/?name=BusinessGuru&background=8b5cf6&color=fff',
    likes: 1650,
    views: 5400,
    tags: ['business', 'strategy', 'analysis', 'SWOT'],
    createdAt: '2024-01-10'
  },
  {
    id: '6',
    title: 'Plan de Marketing Digital 360',
    description: 'Estrategia completa de marketing digital para lanzamientos.',
    content: 'Como CMO experto, diseña plan de marketing digital 360° para lanzamiento de [PRODUCTO]. Incluye: buyer personas, customer journey, estrategia de contenido (SEO, redes sociales), paid ads (Google, Facebook, TikTok), email marketing, influencer marketing y métricas de éxito.',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Marketing,
    author: 'MarketingWiz',
    authorId: 'user-6',
    authorPhoto: 'https://ui-avatars.com/api/?name=MarketingWiz&background=3b82f6&color=fff',
    likes: 2800,
    views: 9200,
    tags: ['marketing', 'digital-strategy', 'launch'],
    createdAt: '2024-02-05'
  },

  // Midjourney Prompts - Design
  {
    id: '7',
    title: 'Fotografía de Producto Profesional',
    description: 'Renders realistas de productos para e-commerce y publicidad.',
    content: '/imagine prompt: professional product photography, [PRODUCT] on minimalist white background, studio lighting setup with key light, fill light and rim light, ultra sharp focus, 85mm lens, f/2.8, commercial photography, 8k resolution, photorealistic --ar 4:5 --style raw --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'ProductShot',
    authorId: 'user-7',
    authorPhoto: 'https://ui-avatars.com/api/?name=ProductShot&background=ef4444&color=fff',
    likes: 4100,
    views: 15000,
    tags: ['midjourney', 'product-photography', 'ecommerce'],
    createdAt: '2024-01-18'
  },
  {
    id: '8',
    title: 'Retrato Cinematográfico Premium',
    description: 'Retratos con calidad de cine para branding personal.',
    content: '/imagine prompt: cinematic portrait photography, professional [PERSON DESCRIPTION], dramatic lighting, Rembrandt lighting setup, bokeh background, shot on Arri Alexa, anamorphic lens, film grain, shallow depth of field, 16k, hyperrealistic --ar 2:3 --style raw --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'CinematicPro',
    authorId: 'user-8',
    authorPhoto: 'https://ui-avatars.com/api/?name=CinematicPro&background=f97316&color=fff',
    likes: 3500,
    views: 11000,
    tags: ['portrait', 'cinematic', 'professional'],
    createdAt: '2024-02-12'
  },
  {
    id: '9',
    title: 'Logo Minimalista Moderno',
    description: 'Diseños de logos corporativos elegantes y versátiles.',
    content: '/imagine prompt: minimalist modern logo design for [BRAND NAME], [INDUSTRY], clean geometric shapes, flat design, vector art style, professional corporate identity, monochrome with accent color, scalable, negative space clever use --no text, mockup --ar 1:1 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'LogoDesigner',
    authorId: 'user-9',
    authorPhoto: 'https://ui-avatars.com/api/?name=LogoDesigner&background=8b5cf6&color=fff',
    likes: 2900,
    views: 8500,
    tags: ['logo', 'branding', 'minimalist', 'corporate'],
    createdAt: '2024-01-22'
  },
  {
    id: '10',
    title: 'Ilustración de Personaje Cartoon',
    description: 'Personajes estilo cartoon para animación y mascota de marca.',
    content: '/imagine prompt: cute cartoon character design, [CHARACTER DESCRIPTION], Disney Pixar style, expressive eyes, friendly smile, full body pose, vibrant colors, clean vector illustration, professional character sheet, white background, animation ready --ar 1:1 --niji 6',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'CartoonMaster',
    authorId: 'user-10',
    authorPhoto: 'https://ui-avatars.com/api/?name=CartoonMaster&background=ec4899&color=fff',
    likes: 3800,
    views: 13000,
    tags: ['cartoon', 'character-design', 'illustration'],
    createdAt: '2024-02-08'
  },

  // Stable Diffusion Prompts
  {
    id: '11',
    title: 'Arte Digital Cyberpunk',
    description: 'Escenas futuristas con estética cyberpunk y neón.',
    content: 'masterpiece, best quality, cyberpunk city street, neon signs, rain-soaked pavement reflections, futuristic vehicles, holographic advertisements, dramatic lighting, night scene, highly detailed, 8k uhd, digital painting, trending on artstation, unreal engine 5',
    imageUrl: 'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?auto=format&fit=crop&q=80&w=800',
    platform: Platform.StableDiffusion,
    category: Category.Design,
    author: 'CyberArtist',
    authorId: 'user-11',
    authorPhoto: 'https://ui-avatars.com/api/?name=CyberArtist&background=06b6d4&color=fff',
    likes: 4500,
    views: 16000,
    tags: ['cyberpunk', 'digital-art', 'futuristic'],
    createdAt: '2024-01-28'
  },
  {
    id: '12',
    title: 'Paisaje de Fantasía Épica',
    description: 'Mundos fantásticos con castillos, dragones y magia.',
    content: 'epic fantasy landscape, ancient castle on mountain peak, dragons flying in sky, magical aurora lights, waterfalls, floating islands, dramatic clouds, golden hour lighting, highly detailed matte painting, concept art, greg rutkowski style, 8k resolution',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    platform: Platform.StableDiffusion,
    category: Category.Design,
    author: 'FantasyWorld',
    authorId: 'user-12',
    authorPhoto: 'https://ui-avatars.com/api/?name=FantasyWorld&background=a855f7&color=fff',
    likes: 5200,
    views: 18500,
    tags: ['fantasy', 'landscape', 'epic', 'magic'],
    createdAt: '2024-02-14'
  },

  // Gemini Prompts
  {
    id: '13',
    title: 'Investigador de Mercado',
    description: 'Análisis profundo de tendencias y comportamiento del consumidor.',
    content: 'Actúa como investigador de mercado experto. Analiza el mercado de [INDUSTRIA/PRODUCTO] en [REGIÓN]. Proporciona: 1) Tamaño de mercado y crecimiento proyectado, 2) Segmentación de clientes con datos demográficos, 3) Análisis de competencia top 5, 4) Tendencias emergentes, 5) Oportunidades de nicho. Incluye fuentes y datos estadísticos.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.Business,
    author: 'DataAnalyst',
    authorId: 'user-13',
    authorPhoto: 'https://ui-avatars.com/api/?name=DataAnalyst&background=0ea5e9&color=fff',
    likes: 1900,
    views: 6800,
    tags: ['market-research', 'analysis', 'trends'],
    createdAt: '2024-01-30'
  },
  {
    id: '14',
    title: 'Profesor de Idiomas Personalizado',
    description: 'Aprende cualquier idioma con práctica conversacional y ejercicios.',
    content: 'Eres profesor nativo de [IDIOMA] con certificación CEFR. Crea plan de aprendizaje personalizado para nivel [A1/A2/B1/B2/C1]. Incluye: vocabulario temático semanal, ejercicios de gramática, conversaciones simuladas, corrección de pronunciación y recursos adicionales (podcasts, libros, películas). Corrige mis errores y explica.',
    imageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.General,
    author: 'LanguageTeach',
    authorId: 'user-14',
    authorPhoto: 'https://ui-avatars.com/api/?name=LanguageTeach&background=14b8a6&color=fff',
    likes: 3100,
    views: 11500,
    tags: ['language-learning', 'education', 'conversation'],
    createdAt: '2024-02-03'
  },

  // More ChatGPT - Coding
  {
    id: '15',
    title: 'Optimizador de SQL Queries',
    description: 'Mejora performance de consultas SQL complejas.',
    content: 'Eres DBA Senior especializado en optimización de bases de datos. Analiza esta query SQL y proporciona versión optimizada. Incluye: 1) Explain plan analysis, 2) Índices sugeridos, 3) Query refactorizada, 4) Estimación de mejora de performance, 5) Mejores prácticas aplicadas:\n\n[PEGA TU SQL QUERY]',
    imageUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'SQLExpert',
    authorId: 'user-15',
    authorPhoto: 'https://ui-avatars.com/api/?name=SQLExpert&background=6366f1&color=fff',
    likes: 2200,
    views: 7500,
    tags: ['sql', 'database', 'optimization', 'performance'],
    createdAt: '2024-01-12'
  },
  {
    id: '16',
    title: 'Generador de Tests Unitarios',
    description: 'Crea tests comprehensivos con Jest, Pytest o JUnit.',
    content: 'Actúa como QA Engineer especializado en TDD. Genera tests unitarios comprehensivos para este código usando [Jest/Pytest/JUnit]. Incluye: casos positivos, casos edge, manejo de errores, mocks necesarios, cobertura >90%. Explica cada test:\n\n[CÓDIGO A TESTEAR]',
    imageUrl: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'TestMaster',
    authorId: 'user-16',
    authorPhoto: 'https://ui-avatars.com/api/?name=TestMaster&background=10b981&color=fff',
    likes: 1800,
    views: 6200,
    tags: ['testing', 'TDD', 'unit-tests', 'QA'],
    createdAt: '2024-02-16'
  },
  {
    id: '17',
    title: 'Code Reviewer Experto',
    description: 'Revisión de código con mejores prácticas y seguridad.',
    content: 'Eres Senior Code Reviewer. Revisa este código buscando: 1) Bugs potenciales, 2) Vulnerabilidades de seguridad (OWASP Top 10), 3) Code smells, 4) Violaciones de SOLID, 5) Performance issues, 6) Falta de tests. Proporciona sugerencias específicas con ejemplos:\n\n[CÓDIGO]',
    imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'CodeReviewer',
    authorId: 'user-17',
    authorPhoto: 'https://ui-avatars.com/api/?name=CodeReviewer&background=f59e0b&color=fff',
    likes: 2600,
    views: 8900,
    tags: ['code-review', 'best-practices', 'security'],
    createdAt: '2024-01-20'
  },

  // ChatGPT - Marketing
  {
    id: '18',
    title: 'Estratega de Contenido SEO',
    description: 'Plan de contenido optimizado para rankear en Google.',
    content: 'Como SEO Content Strategist, crea plan de contenido mensual para [NICHO/INDUSTRIA]. Incluye: 1) 20 keywords long-tail (volumen, dificultad), 2) Cluster de contenido (pillar + supporting), 3) Calendario editorial, 4) Títulos H1 optimizados, 5) Meta descriptions, 6) Estrategia de link building interno.',
    imageUrl: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Marketing,
    author: 'SEOStrategy',
    authorId: 'user-18',
    authorPhoto: 'https://ui-avatars.com/api/?name=SEOStrategy&background=3b82f6&color=fff',
    likes: 3400,
    views: 12500,
    tags: ['SEO', 'content-strategy', 'keywords'],
    createdAt: '2024-02-10'
  },
  {
    id: '19',
    title: 'Social Media Manager Pro',
    description: 'Contenido viral para Instagram, TikTok y LinkedIn.',
    content: 'Actúa como Social Media Manager experto. Crea calendario de contenido semanal para [MARCA/NICHO] en Instagram, TikTok y LinkedIn. Incluye: 1) 21 ideas de posts (7 por plataforma), 2) Captions con hooks y CTAs, 3) Hashtags estratégicos (#trending + #nicho), 4) Mejores horarios de publicación, 5) Ideas de Reels/Stories.',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Marketing,
    author: 'SocialPro',
    authorId: 'user-19',
    authorPhoto: 'https://ui-avatars.com/api/?name=SocialPro&background=ec4899&color=fff',
    likes: 4200,
    views: 14800,
    tags: ['social-media', 'instagram', 'tiktok', 'content'],
    createdAt: '2024-01-26'
  },
  {
    id: '20',
    title: 'Analista de Google Ads',
    description: 'Optimiza campañas PPC para máximo ROI.',
    content: 'Como Google Ads Specialist certificado, analiza y optimiza esta campaña PPC. Proporciona: 1) Estructura de cuenta recomendada, 2) Grupos de anuncios por intención, 3) Anuncios RSA con extensiones, 4) Estrategia de puja (CPA/ROAS target), 5) Negative keywords, 6) A/B testing plan. Datos: [INDUSTRIA, BUDGET, OBJETIVO]',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Marketing,
    author: 'PPCExpert',
    authorId: 'user-20',
    authorPhoto: 'https://ui-avatars.com/api/?name=PPCExpert&background=ef4444&color=fff',
    likes: 2800,
    views: 9600,
    tags: ['google-ads', 'PPC', 'advertising', 'ROI'],
    createdAt: '2024-02-07'
  },

  // Claude - Writing
  {
    id: '21',
    title: 'Escritor de Guiones de Video',
    description: 'Scripts para YouTube, TikTok y video marketing.',
    content: 'Eres guionista profesional de videos virales. Escribe script de [DURACIÓN] minutos para [YouTube/TikTok/Instagram] sobre [TEMA]. Estructura: Hook 3 segundos, introducción problema, solución paso a paso, CTA final. Incluye timing de cortes, B-rolls sugeridos y música mood. Tono: [educativo/entretenido/motivacional].',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Writing,
    author: 'VideoScript',
    authorId: 'user-21',
    authorPhoto: 'https://ui-avatars.com/api/?name=VideoScript&background=8b5cf6&color=fff',
    likes: 3900,
    views: 13200,
    tags: ['video-script', 'youtube', 'content-creation'],
    createdAt: '2024-01-17'
  },
  {
    id: '22',
    title: 'Autor de Ebooks Bestseller',
    description: 'Outline completo y primeros capítulos de libros digitales.',
    content: 'Actúa como autor bestseller de Amazon. Crea outline completo para ebook de [TEMA/NICHO]. Incluye: 1) Título magnético + subtitle, 2) Tabla de contenidos con 10 capítulos, 3) Resumen de cada capítulo (100 palabras), 4) Puntos clave y takeaways, 5) Introducción completa del libro (500 palabras). Target: [AUDIENCIA].',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Writing,
    author: 'EbookAuthor',
    authorId: 'user-22',
    authorPhoto: 'https://ui-avatars.com/api/?name=EbookAuthor&background=f59e0b&color=fff',
    likes: 2500,
    views: 8300,
    tags: ['ebook', 'writing', 'publishing', 'amazon'],
    createdAt: '2024-02-11'
  },

  // Midjourney - Advanced
  {
    id: '23',
    title: 'Arquitectura Interior Luxury',
    description: 'Renders de diseño interior de alta gama.',
    content: '/imagine prompt: luxury modern interior design, [ROOM TYPE], minimalist scandinavian style, natural lighting through floor-to-ceiling windows, premium materials (marble, wood, brass accents), designer furniture, indoor plants, architectural photography, shot by interior design magazine, 8k ultra detailed --ar 16:9 --style raw --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'InteriorPro',
    authorId: 'user-23',
    authorPhoto: 'https://ui-avatars.com/api/?name=InteriorPro&background=06b6d4&color=fff',
    likes: 4800,
    views: 17000,
    tags: ['interior-design', 'luxury', 'architecture'],
    createdAt: '2024-01-24'
  },
  {
    id: '24',
    title: 'Packaging Design Premium',
    description: 'Diseños de empaque para productos de consumo.',
    content: '/imagine prompt: premium product packaging design, [PRODUCT TYPE], minimalist elegant box, embossed logo, metallic foil details, sustainable eco-friendly materials, studio product shot, clean white background, commercial photography, marketing ready, 8k resolution --ar 4:5 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1575558091186-0e1f0677e645?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'PackDesign',
    authorId: 'user-24',
    authorPhoto: 'https://ui-avatars.com/api/?name=PackDesign&background=a855f7&color=fff',
    likes: 3600,
    views: 12300,
    tags: ['packaging', 'product-design', 'branding'],
    createdAt: '2024-02-18'
  },
  {
    id: '25',
    title: 'Ilustración Editorial Artística',
    description: 'Ilustraciones para revistas, libros y artículos.',
    content: '/imagine prompt: editorial illustration for [TOPIC], conceptual art, sophisticated color palette, metaphorical visual storytelling, New Yorker magazine style, vector art mixed with watercolor texture, professional publication ready --ar 3:4 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'EditorialArt',
    authorId: 'user-25',
    authorPhoto: 'https://ui-avatars.com/api/?name=EditorialArt&background=ef4444&color=fff',
    likes: 3200,
    views: 10800,
    tags: ['editorial', 'illustration', 'magazine', 'art'],
    createdAt: '2024-01-31'
  },

  // ChatGPT - Business
  {
    id: '26',
    title: 'Business Plan Investor-Ready',
    description: 'Plan de negocios completo para pitch de inversión.',
    content: 'Crea business plan completo para pitch de inversión en [STARTUP/PROYECTO]. Incluye: 1) Executive Summary, 2) Problema y Solución, 3) Análisis de mercado TAM/SAM/SOM, 4) Modelo de negocio y revenue streams, 5) Go-to-market strategy, 6) Proyecciones financieras 3 años, 7) Team y advisors, 8) Use of funds. Formato profesional.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Business,
    author: 'StartupExpert',
    authorId: 'user-26',
    authorPhoto: 'https://ui-avatars.com/api/?name=StartupExpert&background=6366f1&color=fff',
    likes: 2900,
    views: 9800,
    tags: ['business-plan', 'startup', 'investment', 'pitch'],
    createdAt: '2024-02-04'
  },
  {
    id: '27',
    title: 'Consultor de Productividad',
    description: 'Sistemas personalizados para máxima productividad.',
    content: 'Eres consultor de productividad certificado GTD. Diseña sistema personalizado de productividad para [PROFESIÓN/SITUACIÓN]. Incluye: 1) Rutina matutina ideal, 2) Sistema de gestión de tareas (Eisenhower matrix aplicada), 3) Time blocking semanal, 4) Herramientas recomendadas (Notion, Todoist), 5) Hábitos para energía sostenida, 6) Métricas de tracking.',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Business,
    author: 'ProductivityPro',
    authorId: 'user-27',
    authorPhoto: 'https://ui-avatars.com/api/?name=ProductivityPro&background=10b981&color=fff',
    likes: 3700,
    views: 12900,
    tags: ['productivity', 'GTD', 'time-management'],
    createdAt: '2024-01-19'
  },

  // Stable Diffusion - Art
  {
    id: '28',
    title: 'Anime Character Design Pro',
    description: 'Personajes anime estilo Studio Ghibli y Makoto Shinkai.',
    content: 'anime character design, [CHARACTER DESCRIPTION], studio ghibli style, makoto shinkai lighting, detailed eyes, soft colors, whimsical atmosphere, high quality anime art, character reference sheet, multiple poses, concept art, trending on pixiv, 4k --ar 2:3',
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&q=80&w=800',
    platform: Platform.StableDiffusion,
    category: Category.Design,
    author: 'AnimeArtist',
    authorId: 'user-28',
    authorPhoto: 'https://ui-avatars.com/api/?name=AnimeArtist&background=ec4899&color=fff',
    likes: 5600,
    views: 19500,
    tags: ['anime', 'character-design', 'ghibli'],
    createdAt: '2024-02-15'
  },
  {
    id: '29',
    title: 'Arte Abstracto Moderno',
    description: 'Composiciones abstractas para decoración y NFTs.',
    content: 'abstract modern art, geometric shapes, vibrant color gradients, fluid dynamics, contemporary art gallery piece, kandinsky inspired, high contrast, symmetrical balance, digital painting, museum quality, 8k uhd, trending on artstation',
    imageUrl: 'https://images.unsplash.com/photo-1549289524-06cf8837ace5?auto=format&fit=crop&q=80&w=800',
    platform: Platform.StableDiffusion,
    category: Category.Design,
    author: 'AbstractPro',
    authorId: 'user-29',
    authorPhoto: 'https://ui-avatars.com/api/?name=AbstractPro&background=8b5cf6&color=fff',
    likes: 4100,
    views: 14200,
    tags: ['abstract', 'modern-art', 'NFT', 'digital-art'],
    createdAt: '2024-01-27'
  },

  // Gemini - Education
  {
    id: '30',
    title: 'Tutor de Matemáticas Avanzadas',
    description: 'Explicaciones paso a paso de cálculo, álgebra y más.',
    content: 'Actúa como profesor de matemáticas universitario. Explica este concepto/problema de [CÁLCULO/ÁLGEBRA/ESTADÍSTICA] paso a paso. Para cada paso: 1) Explica el razonamiento, 2) Muestra el cálculo, 3) Verifica el resultado, 4) Da ejemplo similar. Usa analogías del mundo real. Nivel: [preparatoria/universidad]. Problema: [PROBLEMA]',
    imageUrl: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.General,
    author: 'MathTutor',
    authorId: 'user-30',
    authorPhoto: 'https://ui-avatars.com/api/?name=MathTutor&background=0ea5e9&color=fff',
    likes: 2700,
    views: 9100,
    tags: ['math', 'education', 'tutoring', 'calculus'],
    createdAt: '2024-02-09'
  },

  // Continue with more diverse prompts...
  {
    id: '31',
    title: 'UX Writer Profesional',
    description: 'Microcopy que mejora conversión y UX.',
    content: 'Como UX Writer Senior, crea microcopy para [APP/WEBSITE]. Incluye: 1) Onboarding (3 pantallas), 2) CTA buttons (10 variaciones), 3) Error messages (amigables, accionables), 4) Empty states, 5) Success messages, 6) Tooltips explicativos. Tono de voz: [marca]. Principios: claridad, concisión, utilidad.',
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Writing,
    author: 'UXWriter',
    authorId: 'user-31',
    authorPhoto: 'https://ui-avatars.com/api/?name=UXWriter&background=3b82f6&color=fff',
    likes: 2100,
    views: 7200,
    tags: ['UX-writing', 'microcopy', 'conversion', 'UI'],
    createdAt: '2024-01-13'
  },
  {
    id: '32',
    title: 'Estratega de LinkedIn Personal Branding',
    description: 'Construye autoridad y genera leads en LinkedIn.',
    content: 'Actúa como LinkedIn Growth Strategist. Crea estrategia de personal branding para [PROFESIÓN/NICHO] en LinkedIn. Incluye: 1) Optimización de perfil (About, Featured), 2) Content pillars (4 temas), 3) 30 ideas de posts (carousels, videos, text), 4) Estrategia de engagement, 5) Outreach templates para networking, 6) KPIs y métricas.',
    imageUrl: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Marketing,
    author: 'LinkedInPro',
    authorId: 'user-32',
    authorPhoto: 'https://ui-avatars.com/api/?name=LinkedInPro&background=0077b5&color=fff',
    likes: 3800,
    views: 13500,
    tags: ['linkedin', 'personal-branding', 'networking'],
    createdAt: '2024-02-21'
  },
  {
    id: '33',
    title: 'Diseño de Infografías Virales',
    description: 'Infografías educativas y compartibles.',
    content: '/imagine prompt: professional infographic design about [TOPIC], clean layout, data visualization, icons and charts, modern flat design style, corporate color scheme, easy to read typography, visual hierarchy, social media optimized, high resolution --ar 9:16 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'InfoDesigner',
    authorId: 'user-33',
    authorPhoto: 'https://ui-avatars.com/api/?name=InfoDesigner&background=f97316&color=fff',
    likes: 3300,
    views: 11200,
    tags: ['infographic', 'data-viz', 'design', 'social-media'],
    createdAt: '2024-01-29'
  },
  {
    id: '34',
    title: 'Developer de Prompts de IA',
    description: 'Crea prompts óptimos para cualquier caso de uso.',
    content: 'Eres experto en Prompt Engineering. Diseña prompt optimizado para [CASO DE USO]. Aplica: 1) Role prompting claro, 2) Context window optimization, 3) Few-shot examples, 4) Chain-of-thought reasoning, 5) Output formatting específico, 6) Temperature y parámetros sugeridos. Prueba con 3 variaciones y compara resultados.',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'PromptEngineer',
    authorId: 'user-34',
    authorPhoto: 'https://ui-avatars.com/api/?name=PromptEngineer&background=6366f1&color=fff',
    likes: 4500,
    views: 15800,
    tags: ['prompt-engineering', 'AI', 'optimization'],
    createdAt: '2024-02-13'
  },
  {
    id: '35',
    title: 'Recruiter Tech Especializado',
    description: 'Entrevistas técnicas y evaluación de candidatos.',
    content: 'Eres Technical Recruiter senior en FAANG. Diseña proceso de entrevista completo para [POSICIÓN]. Incluye: 1) Job description optimizada (ATS-friendly), 2) 30 preguntas técnicas (junior/mid/senior), 3) Coding challenges con rubrica, 4) Behavioral questions STAR, 5) Sistema de scoring, 6) Red flags a detectar, 7) Onboarding checklist.',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Business,
    author: 'TechRecruiter',
    authorId: 'user-35',
    authorPhoto: 'https://ui-avatars.com/api/?name=TechRecruiter&background=10b981&color=fff',
    likes: 2400,
    views: 8100,
    tags: ['recruitment', 'tech-hiring', 'interviews'],
    createdAt: '2024-01-16'
  },

  // Adding 15 more to reach 50
  {
    id: '36',
    title: 'Fotógrafo de Gastronomía',
    description: 'Food photography profesional para menús y redes.',
    content: '/imagine prompt: professional food photography, [DISH NAME], gourmet plating, natural daylight, rustic wood table, selective focus, garnish details, steam rising, appetizing composition, shot from 45-degree angle, food magazine quality, 8k resolution --ar 4:5 --style raw --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'FoodPhoto',
    authorId: 'user-36',
    authorPhoto: 'https://ui-avatars.com/api/?name=FoodPhoto&background=f59e0b&color=fff',
    likes: 4700,
    views: 16400,
    tags: ['food-photography', 'gastronomy', 'restaurant'],
    createdAt: '2024-02-17'
  },
  {
    id: '37',
    title: 'Asesor Financiero Personal',
    description: 'Planificación financiera y estrategias de inversión.',
    content: 'Actúa como CFP (Certified Financial Planner). Crea plan financiero personalizado para [PERFIL: edad, ingresos, objetivos]. Incluye: 1) Presupuesto optimizado 50/30/20, 2) Fondo de emergencia (6 meses), 3) Estrategia de inversión (acciones, ETFs, crypto %), 4) Plan de retiro, 5) Seguros necesarios, 6) Tax optimization, 7) Proyección 10-20-30 años.',
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.Business,
    author: 'FinancialAdvisor',
    authorId: 'user-37',
    authorPhoto: 'https://ui-avatars.com/api/?name=FinancialAdvisor&background=059669&color=fff',
    likes: 3100,
    views: 10500,
    tags: ['finance', 'investment', 'planning', 'wealth'],
    createdAt: '2024-01-23'
  },
  {
    id: '38',
    title: 'Escritor de Newsletters Virales',
    description: 'Newsletters que se abren y se comparten.',
    content: 'Como newsletter writer con >50% open rate, escribe newsletter semanal para [NICHO]. Estructura: 1) Subject line irresistible (A/B test 2 opciones), 2) Hook opening (primera línea), 3) Historia personal relatable, 4) 3 insights valiosos, 5) CTA claro, 6) PS con bonus. Tono: conversacional, personal. Largo: 500-700 palabras.',
    imageUrl: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Writing,
    author: 'NewsletterPro',
    authorId: 'user-38',
    authorPhoto: 'https://ui-avatars.com/api/?name=NewsletterPro&background=ec4899&color=fff',
    likes: 3500,
    views: 12100,
    tags: ['newsletter', 'email', 'content', 'writing'],
    createdAt: '2024-02-19'
  },
  {
    id: '39',
    title: 'Diseñador UI/UX Moderno',
    description: 'Mockups de interfaces modernas y funcionales.',
    content: '/imagine prompt: modern UI/UX design for [APP/WEBSITE], clean interface, neumorphism elements, glassmorphism cards, micro-interactions, mobile-first responsive, Figma design, contemporary color palette, user-friendly navigation, professional mockup --ar 16:9 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'UIDesigner',
    authorId: 'user-39',
    authorPhoto: 'https://ui-avatars.com/api/?name=UIDesigner&background=8b5cf6&color=fff',
    likes: 4300,
    views: 14900,
    tags: ['UI', 'UX', 'design', 'mockup', 'interface'],
    createdAt: '2024-01-11'
  },
  {
    id: '40',
    title: 'Coach de Vida Certificado',
    description: 'Guía personalizada para alcanzar metas personales.',
    content: 'Eres Life Coach certificado ICF. Crea plan de transformación de 90 días para [OBJETIVO: carrera, relaciones, salud]. Método SMART goals. Incluye: 1) Evaluación situación actual (Rueda de la vida), 2) Visión clara del futuro deseado, 3) Objetivos semanales específicos, 4) Hábitos diarios clave, 5) Ejercicios de mindset, 6) Sistema de accountability, 7) Celebración de wins.',
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.General,
    author: 'LifeCoach',
    authorId: 'user-40',
    authorPhoto: 'https://ui-avatars.com/api/?name=LifeCoach&background=14b8a6&color=fff',
    likes: 2900,
    views: 9900,
    tags: ['life-coaching', 'goals', 'personal-development'],
    createdAt: '2024-02-22'
  },
  {
    id: '41',
    title: 'Generador de Nombres de Marca',
    description: 'Naming creativo con dominio y trademark disponible.',
    content: 'Eres branding specialist y naming expert. Genera 30 nombres de marca para [INDUSTRIA/PRODUCTO]. Criterios: 1) Memorable y único, 2) Fácil de pronunciar, 3) Disponible como .com, 4) Sin conflictos de trademark, 5) Evoca emociones correctas. Para top 10: explica significado, audiencia target y por qué funciona. Estilos: inventados, descriptivos, compound words.',
    imageUrl: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Business,
    author: 'BrandNamer',
    authorId: 'user-41',
    authorPhoto: 'https://ui-avatars.com/api/?name=BrandNamer&background=f97316&color=fff',
    likes: 2600,
    views: 8800,
    tags: ['branding', 'naming', 'trademark', 'domains'],
    createdAt: '2024-01-14'
  },
  {
    id: '42',
    title: 'Ilustración Isométrica 3D',
    description: 'Ilustraciones isométricas para tech y SaaS.',
    content: '/imagine prompt: isometric 3D illustration of [CONCEPT], clean geometric shapes, modern tech aesthetic, vibrant gradient colors, floating elements, depth and dimension, SaaS landing page style, vector art, professional digital illustration --ar 16:9 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'IsometricPro',
    authorId: 'user-42',
    authorPhoto: 'https://ui-avatars.com/api/?name=IsometricPro&background=06b6d4&color=fff',
    likes: 3900,
    views: 13400,
    tags: ['isometric', '3D', 'illustration', 'SaaS', 'tech'],
    createdAt: '2024-02-06'
  },
  {
    id: '43',
    title: 'Desarrollador de Chatbots IA',
    description: 'Diseña flujos de conversación y personalidades de bots.',
    content: 'Eres Conversational AI Designer. Diseña chatbot para [INDUSTRIA/USE-CASE]. Incluye: 1) Personalidad del bot (tono, estilo), 2) Árbol de decisiones de conversación, 3) 50+ intents con ejemplos, 4) Responses naturales (no robóticas), 5) Fallback messages creativos, 6) Handoff humano criterios, 7) Métricas de éxito. Plataforma: [Dialogflow/Rasa/GPT].',
    imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'ChatbotDev',
    authorId: 'user-43',
    authorPhoto: 'https://ui-avatars.com/api/?name=ChatbotDev&background=6366f1&color=fff',
    likes: 2200,
    views: 7400,
    tags: ['chatbot', 'AI', 'conversation-design', 'NLP'],
    createdAt: '2024-01-21'
  },
  {
    id: '44',
    title: 'Presentaciones Pitch Deck Ganadoras',
    description: 'Slides de investor pitch que cierran fondeo.',
    content: 'Crea pitch deck de 12 slides para levantar [CANTIDAD] en ronda [Seed/Serie A]. Estructura: 1) Problem (historia relatable), 2) Solution, 3) Market size (TAM/SAM/SOM), 4) Product (demo con screenshots), 5) Business model, 6) Traction (métricas clave), 7) Competition, 8) Team, 9) Financials, 10) Use of funds, 11) Vision, 12) Ask. Incluye data points y visuales sugeridos.',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Business,
    author: 'PitchMaster',
    authorId: 'user-44',
    authorPhoto: 'https://ui-avatars.com/api/?name=PitchMaster&background=ef4444&color=fff',
    likes: 3400,
    views: 11700,
    tags: ['pitch-deck', 'fundraising', 'investor', 'startup'],
    createdAt: '2024-02-02'
  },
  {
    id: '45',
    title: 'Arte Pixel Art Retro',
    description: 'Sprites y escenarios estilo videojuegos retro.',
    content: 'pixel art game design, [CHARACTER/SCENE], 16-bit style, retro gaming aesthetic, vibrant color palette, detailed sprites, game ready assets, nostalgic 90s vibe, clean pixelated lines, transparent background --ar 1:1 --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&q=80&w=800',
    platform: Platform.StableDiffusion,
    category: Category.Design,
    author: 'PixelArtist',
    authorId: 'user-45',
    authorPhoto: 'https://ui-avatars.com/api/?name=PixelArtist&background=a855f7&color=fff',
    likes: 5100,
    views: 17800,
    tags: ['pixel-art', 'retro', 'gaming', '16-bit'],
    createdAt: '2024-01-25'
  },
  {
    id: '46',
    title: 'Analista de Datos con Python',
    description: 'Scripts de análisis de datos y visualizaciones.',
    content: 'Eres Data Analyst experto en Python (pandas, matplotlib, seaborn). Analiza este dataset y proporciona: 1) EDA completo (describe, info, missing values), 2) Visualizaciones clave (distribuciones, correlaciones), 3) Insights principales encontrados, 4) Outliers y anomalías, 5) Sugerencias de limpieza, 6) Next steps para modeling. Dataset: [DESCRIPCIÓN/LINK]',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'DataScientist',
    authorId: 'user-46',
    authorPhoto: 'https://ui-avatars.com/api/?name=DataScientist&background=0ea5e9&color=fff',
    likes: 2800,
    views: 9500,
    tags: ['data-analysis', 'python', 'pandas', 'visualization'],
    createdAt: '2024-02-20'
  },
  {
    id: '47',
    title: 'Experto en Facebook Ads',
    description: 'Campañas de Facebook/Instagram Ads optimizadas.',
    content: 'Como Facebook Ads Manager con $10M+ spend, diseña campaña completa para [OBJETIVO: ventas/leads/branding]. Incluye: 1) Estructura de campaña (ToFu/MoFu/BoFu), 2) Audiencias custom + lookalike, 3) 5 ad creatives (copy + visual direction), 4) Landing page recomendaciones, 5) Pixel tracking setup, 6) Budget allocation, 7) Scaling strategy. Budget: [CANTIDAD]',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Claude,
    category: Category.Marketing,
    author: 'FBAdsExpert',
    authorId: 'user-47',
    authorPhoto: 'https://ui-avatars.com/api/?name=FBAdsExpert&background=1877f2&color=fff',
    likes: 3200,
    views: 11000,
    tags: ['facebook-ads', 'instagram', 'paid-social'],
    createdAt: '2024-01-18'
  },
  {
    id: '48',
    title: 'Renders de Moda Editorial',
    description: 'Fashion photography para campañas y lookbooks.',
    content: '/imagine prompt: high fashion editorial photography, [OUTFIT/STYLE DESCRIPTION], professional model, vogue magazine style, dramatic lighting, urban backdrop or studio, designer clothing, trendy pose, haute couture aesthetic, shot by fashion photographer, 8k resolution --ar 2:3 --style raw --v 6',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Midjourney,
    category: Category.Design,
    author: 'FashionPhoto',
    authorId: 'user-48',
    authorPhoto: 'https://ui-avatars.com/api/?name=FashionPhoto&background=ec4899&color=fff',
    likes: 4600,
    views: 16100,
    tags: ['fashion', 'photography', 'editorial', 'haute-couture'],
    createdAt: '2024-02-23'
  },
  {
    id: '49',
    title: 'Mentor de Fitness Personalizado',
    description: 'Planes de entrenamiento y nutrición customizados.',
    content: 'Actúa como Personal Trainer certificado NSCA y nutricionista. Diseña plan de 12 semanas para [OBJETIVO: pérdida grasa/ganancia muscular/rendimiento]. Perfil: [edad, peso, altura, experiencia]. Incluye: 1) Split de entrenamiento (días/grupos musculares), 2) Ejercicios específicos con sets/reps, 3) Plan nutricional con macros, 4) Meal prep ideas, 5) Suplementación, 6) Progresión semanal, 7) Recovery protocols.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
    platform: Platform.Gemini,
    category: Category.General,
    author: 'FitnessMentor',
    authorId: 'user-49',
    authorPhoto: 'https://ui-avatars.com/api/?name=FitnessMentor&background=059669&color=fff',
    likes: 3600,
    views: 12400,
    tags: ['fitness', 'workout', 'nutrition', 'health'],
    createdAt: '2024-01-15'
  },
  {
    id: '50',
    title: 'Arquitecto de Software Senior',
    description: 'Diseño de arquitecturas escalables y resilientes.',
    content: 'Eres Software Architect en empresa Fortune 500. Diseña arquitectura para sistema [DESCRIPCIÓN]. Incluye: 1) Diagrama C4 (Context, Containers, Components), 2) Tech stack recomendado con justificación, 3) Patrones de diseño aplicados (CQRS, Event Sourcing, etc), 4) Estrategia de database (SQL/NoSQL, sharding), 5) Caching layer, 6) Security considerations, 7) Escalabilidad horizontal, 8) Disaster recovery. Stack preferido: [TECH]',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800',
    platform: Platform.ChatGPT,
    category: Category.Coding,
    author: 'SoftwareArch',
    authorId: 'user-50',
    authorPhoto: 'https://ui-avatars.com/api/?name=SoftwareArch&background=6366f1&color=fff',
    likes: 3100,
    views: 10600,
    tags: ['architecture', 'system-design', 'scalability'],
    createdAt: '2024-02-24'
  },
];
